Traceback (most recent call last):
  File "C:\Users\pedan\PycharmProjects\python-doc\08-Exception handling\main.py", line 4, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
